# Generated by Django 5.0.1 on 2024-01-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quintity',
            new_name='quantity',
        ),
    ]
