# Generated by Django 5.0.1 on 2024-01-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='usesr',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='usesr',
            new_name='user',
        ),
    ]
